-- MySQL Script generated by MySQL Workbench
-- Thu Dec  2 16:18:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BaseballCardCollectors
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `RARITIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RARITIES` ;

CREATE TABLE IF NOT EXISTS `RARITIES` (
  `idRarity` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idRarity`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idRarity_UNIQUE` ON `RARITIES` (`idRarity` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `SERIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SERIES` ;

CREATE TABLE IF NOT EXISTS `SERIES` (
  `idSerie` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(20) NOT NULL,
  `publicationDate` DATE NOT NULL,
  PRIMARY KEY (`idSerie`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idSerie_UNIQUE` ON `SERIES` (`idSerie` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PLAYERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PLAYERS` ;

CREATE TABLE IF NOT EXISTS `PLAYERS` (
  `idPlayer` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `picture` VARCHAR(50) NULL,
  PRIMARY KEY (`idPlayer`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPlayer_UNIQUE` ON `PLAYERS` (`idPlayer` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TEAMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEAMS` ;

CREATE TABLE IF NOT EXISTS `TEAMS` (
  `idTeam` INT NOT NULL AUTO_INCREMENT,
  `teamName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idTeam`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idTeam_UNIQUE` ON `TEAMS` (`idTeam` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PLAYER_ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PLAYER_ROLES` ;

CREATE TABLE IF NOT EXISTS `PLAYER_ROLES` (
  `idPlayerRole` INT NOT NULL AUTO_INCREMENT,
  `nameRole` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idPlayerRole`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPlayerRole_UNIQUE` ON `PLAYER_ROLES` (`idPlayerRole` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PLAYER_CAREER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PLAYER_CAREER` ;

CREATE TABLE IF NOT EXISTS `PLAYER_CAREER` (
  `idPlayerCareer` INT NOT NULL AUTO_INCREMENT,
  `season` DATE NOT NULL,
  `fk_idPlayer` INT NOT NULL,
  `fk_idTeam` INT NOT NULL,
  `fk_idPlayerRole` INT NOT NULL,
  PRIMARY KEY (`idPlayerCareer`),
  CONSTRAINT `fk_PLAYER_CAREER_PLAYERS1`
    FOREIGN KEY (`fk_idPlayer`)
    REFERENCES `PLAYERS` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYER_CAREER_TEAMS1`
    FOREIGN KEY (`fk_idTeam`)
    REFERENCES `TEAMS` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYER_CAREER_PLAYER_ROLES1`
    FOREIGN KEY (`fk_idPlayerRole`)
    REFERENCES `PLAYER_ROLES` (`idPlayerRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPlayerCareer_UNIQUE` ON `PLAYER_CAREER` (`idPlayerCareer` ASC) VISIBLE;

CREATE INDEX `fk_PLAYER_CAREER_PLAYERS1_idx` ON `PLAYER_CAREER` (`fk_idPlayer` ASC) VISIBLE;

CREATE INDEX `fk_PLAYER_CAREER_TEAMS1_idx` ON `PLAYER_CAREER` (`fk_idTeam` ASC) VISIBLE;

CREATE INDEX `fk_PLAYER_CAREER_PLAYER_ROLES1_idx` ON `PLAYER_CAREER` (`fk_idPlayerRole` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `CARDS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARDS` ;

CREATE TABLE IF NOT EXISTS `CARDS` (
  `idCard` INT NOT NULL AUTO_INCREMENT,
  `fk_idRarity` INT NOT NULL,
  `fk_idSerie` INT NOT NULL,
  `fk_playerCareer` INT NOT NULL,
  PRIMARY KEY (`idCard`),
  CONSTRAINT `fk_CARTAS_RAREZAS1`
    FOREIGN KEY (`fk_idRarity`)
    REFERENCES `RARITIES` (`idRarity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARDS_SERIES1`
    FOREIGN KEY (`fk_idSerie`)
    REFERENCES `SERIES` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARDS_PLAYER_CAREER1`
    FOREIGN KEY (`fk_playerCareer`)
    REFERENCES `PLAYER_CAREER` (`idPlayerCareer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CARTAS_RAREZAS1_idx` ON `CARDS` (`fk_idRarity` ASC) VISIBLE;

CREATE INDEX `fk_CARDS_SERIES1_idx` ON `CARDS` (`fk_idSerie` ASC) VISIBLE;

CREATE UNIQUE INDEX `idCard_UNIQUE` ON `CARDS` (`idCard` ASC) VISIBLE;

CREATE INDEX `fk_CARDS_PLAYER_CAREER1_idx` ON `CARDS` (`fk_playerCareer` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `USERS_ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USERS_ROLES` ;

CREATE TABLE IF NOT EXISTS `USERS_ROLES` (
  `idUserRole` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idUserRole`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idUserRole_UNIQUE` ON `USERS_ROLES` (`idUserRole` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USERS` ;

CREATE TABLE IF NOT EXISTS `USERS` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(20) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `mail` VARCHAR(40) NOT NULL,
  `fk_idUserRole` INT NOT NULL,
  `isActive` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `fk_USUARIOS_ROLES`
    FOREIGN KEY (`fk_idUserRole`)
    REFERENCES `USERS_ROLES` (`idUserRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_USUARIOS_ROLES_idx` ON `USERS` (`fk_idUserRole` ASC) VISIBLE;

CREATE UNIQUE INDEX `idUser_UNIQUE` ON `USERS` (`idUser` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `USERS` (`userName` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `USERS_CARDS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USERS_CARDS` ;

CREATE TABLE IF NOT EXISTS `USERS_CARDS` (
  `fk_idCard` INT NOT NULL,
  `fk_idUser` INT NOT NULL,
  `amount` INT NULL,
  PRIMARY KEY (`fk_idCard`, `fk_idUser`),
  CONSTRAINT `fk_CARTAS_has_USUARIOS_CARTAS1`
    FOREIGN KEY (`fk_idCard`)
    REFERENCES `CARDS` (`idCard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARTAS_has_USUARIOS_USUARIOS1`
    FOREIGN KEY (`fk_idUser`)
    REFERENCES `USERS` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CARTAS_has_USUARIOS_USUARIOS1_idx` ON `USERS_CARDS` (`fk_idUser` ASC) VISIBLE;

CREATE INDEX `fk_CARTAS_has_USUARIOS_CARTAS1_idx` ON `USERS_CARDS` (`fk_idCard` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `COLLECTIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `COLLECTIONS` ;

CREATE TABLE IF NOT EXISTS `COLLECTIONS` (
  `idCollection` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(30) NOT NULL,
  `fk_idSerie` INT NOT NULL,
  PRIMARY KEY (`idCollection`),
  CONSTRAINT `fk_COLLECTIONS_SERIES1`
    FOREIGN KEY (`fk_idSerie`)
    REFERENCES `SERIES` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idCollection_UNIQUE` ON `COLLECTIONS` (`idCollection` ASC) VISIBLE;

CREATE INDEX `fk_COLLECTIONS_SERIES1_idx` ON `COLLECTIONS` (`fk_idSerie` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `COLLECTIONS_CARDS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `COLLECTIONS_CARDS` ;

CREATE TABLE IF NOT EXISTS `COLLECTIONS_CARDS` (
  `fk_idCard` INT NOT NULL,
  `fk_idCollection` INT NOT NULL,
  PRIMARY KEY (`fk_idCard`, `fk_idCollection`),
  CONSTRAINT `fk_CARDS_has_COLLECTIONS_CARDS1`
    FOREIGN KEY (`fk_idCard`)
    REFERENCES `CARDS` (`idCard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARDS_has_COLLECTIONS_COLLECTIONS1`
    FOREIGN KEY (`fk_idCollection`)
    REFERENCES `COLLECTIONS` (`idCollection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CARDS_has_COLLECTIONS_COLLECTIONS1_idx` ON `COLLECTIONS_CARDS` (`fk_idCollection` ASC) VISIBLE;

CREATE INDEX `fk_CARDS_has_COLLECTIONS_CARDS1_idx` ON `COLLECTIONS_CARDS` (`fk_idCard` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `table1` ;

CREATE TABLE IF NOT EXISTS `table1` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
