-- user role

insert into USERS_ROLES(name) values ('admin');
insert into USERS_ROLES(name) values ('collector');

-- collectors

insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('ptamblingson0', 'p9QQuZnkuHS', 'cbegin0@woothemes.com', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('sbeese1', 'cHAE6nUOJHHW', 'ncramb1@shinystat.com', 2, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('ssegeswoeth2', 'KqzCXh', 'gconyers2@paginegialle.it', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('gsilverson3', 'k3T1vLxR', 'ikirsop3@scribd.com', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('tmizzen4', '4POslNB', 'ofigiovanni4@rediff.com', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('dpiers5', 'k7SceG6R4on', 'mgavrieli5@gravatar.com', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('nbart6', 'a8gx74', 'mmacfadzan6@flickr.com', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('rogers7', 'tEZ6fd4u', 'gmclurg7@ihg.com', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('chartington8', 'Q0KDgUY7t', 'bmeriguet8@hp.com', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('itumielli9', 'ucdQXqpNbNw', 'mcron9@si.edu', 2, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('mklaussena', 'CkAanRQvX', 'kmaypesa@washington.edu', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('gdenialb', 'z3Nwcb', 'lchastaingb@ebay.com', 2, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('hnewissc', 'LWXoHU9V', 'rtemlettc@mail.ru', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('uforryand', 'a2U4OQ', 'tdamrelld@eventbrite.com', 2, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('svennerse', 'A24lo7BPSC', 'bvollame@google.ru', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('bechlinf', 'JiPQDUK8ppTC', 'bcosgravef@oaic.gov.au', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('ctyghtg', 'oZcEXI1', 'emcgrottyg@techcrunch.com', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('crenadh', '3BLitKVMRzCm', 'tlavigneh@usa.gov', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('bpopelayi', 'r4uySWkLKMUA', 'lgurneyi@usa.gov', 2, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('hmcgurkj', 'GeCiCCOrN', 'grizzij@nytimes.com', 2, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('broomek', 'gIynG0', 'nduckitk@toplist.cz', 2, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('rclewl', 'BctPjPJwFh5', 'cgrzegoreckil@psu.edu', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('dbirchettm', 'QNdbTgy', 'wthibodeauxm@bizjournals.com', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('hmaughann', 'ufBcIt', 'mwelfaren@plala.or.jp', 2, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('hconkayo', 'rc6UcHdK2vpY', 'ssalvidgeo@instagram.com', 2, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('mbiaggellip', 'MktMl9SIHc', 'srichmondp@ox.ac.uk', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('hblamireq', 'Tif09RP8JT', 'egubbinsq@myspace.com', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('kmidfordr', 'e6dR94lA', 'sbazeleyr@indiegogo.com', 2, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('fhawkeswoods', 'WyIdM3BQqk', 'epeirones@homestead.com', 2, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('mlipproset', 'GqeiKwj', 'bcorballist@taobao.com', 2, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('cguerrieriu', 'RaOtBNjBF0', 'mwarcupu@upenn.edu', 2, true);

-- admins
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('cbingham0', '0WjJ9moX', 'dclayden0@ft.com', 1, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('cpethick1', 'sDJHAgSP', 'bbryce1@google.es', 1, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('erignold2', '21oDmCjwFZxi', 'pgrogor2@jiathis.com', 1, false);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('fhek3', 'Pqum8Oqk7V34', 'dhedger3@fotki.com', 1, true);
insert into USERS (userName, password, mail, fk_idUserRole, isActive) values ('rmaher4', 'H5pqbAOChw', 'lcristofvao4@studiopress.com', 1, false);

-- RARITIES
insert into RARITIES (description) values ('gold');
insert into RARITIES (description) values ('silver');
insert into RARITIES (description) values ('bronze');
insert into RARITIES (description) values ('gold');
insert into RARITIES (description) values ('platinum');


-- PLAYERS
insert into PLAYERS (firstName, lastName, picture) values ('Melly', 'Jonson', 'http://dummyimage.com/171x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Wilone', 'Fiddiman', 'http://dummyimage.com/188x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Austina', 'Lennard', 'http://dummyimage.com/144x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Jory', 'Iacobacci', 'http://dummyimage.com/140x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Angy', 'Szymanzyk', 'http://dummyimage.com/184x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Sigismund', 'Overland', 'http://dummyimage.com/178x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Chickie', 'Killbey', 'http://dummyimage.com/172x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Robb', 'Peddel', 'http://dummyimage.com/211x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Ettie', 'Pickles', 'http://dummyimage.com/135x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Decca', 'Andrioni', 'http://dummyimage.com/183x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Yank', 'Garm', 'http://dummyimage.com/236x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Jess', 'Murdy', 'http://dummyimage.com/167x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Lydon', 'Woolvett', 'http://dummyimage.com/154x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Mischa', 'Eyckelberg', 'http://dummyimage.com/142x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Justen', 'Wakeling', 'http://dummyimage.com/125x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Garreth', 'Schoolcroft', 'http://dummyimage.com/150x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Katya', 'Rohlfs', 'http://dummyimage.com/194x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Karon', 'Robottom', 'http://dummyimage.com/214x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Smith', 'Siveter', 'http://dummyimage.com/106x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Dawna', 'Buxsy', 'http://dummyimage.com/189x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Eadie', 'Royson', 'http://dummyimage.com/194x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Annecorinne', 'Dudden', 'http://dummyimage.com/130x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Deidre', 'Zamora', 'http://dummyimage.com/119x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Karlie', 'Ferriby', 'http://dummyimage.com/172x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Carmine', 'Berzen', 'http://dummyimage.com/139x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Adham', 'Beddow', 'http://dummyimage.com/224x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Melisent', 'Allberry', 'http://dummyimage.com/151x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Shel', 'Jandac', 'http://dummyimage.com/110x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Jeanine', 'Kitteringham', 'http://dummyimage.com/207x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Andonis', 'Embery', 'http://dummyimage.com/218x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Theobald', 'Pirdy', 'http://dummyimage.com/150x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Jory', 'Philpin', 'http://dummyimage.com/229x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Lamar', 'Carlisle', 'http://dummyimage.com/201x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Benetta', 'Twizell', 'http://dummyimage.com/108x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Zorah', 'McIleen', 'http://dummyimage.com/161x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Vina', 'Jantot', 'http://dummyimage.com/110x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Gerard', 'Dorking', 'http://dummyimage.com/185x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Appolonia', 'Porker', 'http://dummyimage.com/188x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Byron', 'Easman', 'http://dummyimage.com/167x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Melinda', 'Haslewood', 'http://dummyimage.com/154x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Helge', 'Winspear', 'http://dummyimage.com/152x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Hanna', 'Blackadder', 'http://dummyimage.com/119x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Ivett', 'Heibel', 'http://dummyimage.com/228x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Mackenzie', 'Hawney', 'http://dummyimage.com/147x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Bennie', 'Choak', 'http://dummyimage.com/109x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Hilario', 'Hasling', 'http://dummyimage.com/144x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Marcello', 'Orto', 'http://dummyimage.com/181x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Curry', 'Melland', 'http://dummyimage.com/160x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Frederik', 'Ashman', 'http://dummyimage.com/161x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Corene', 'Grigoriev', 'http://dummyimage.com/169x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Vite', 'Capewell', 'http://dummyimage.com/239x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Roderick', 'Sandys', 'http://dummyimage.com/125x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Adan', 'Deyes', 'http://dummyimage.com/141x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Gladi', 'Smitton', 'http://dummyimage.com/108x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Gardener', 'Riddoch', 'http://dummyimage.com/118x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Tibold', 'Loynes', 'http://dummyimage.com/120x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Gal', 'Angless', 'http://dummyimage.com/150x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Burr', 'Bignell', 'http://dummyimage.com/216x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Giacinta', 'Robatham', 'http://dummyimage.com/177x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Crissy', 'Hunnable', 'http://dummyimage.com/137x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Caresse', 'Kiernan', 'http://dummyimage.com/217x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Kipp', 'Ovendon', 'http://dummyimage.com/204x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Hunt', 'Pepper', 'http://dummyimage.com/230x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Libbie', 'Pyrton', 'http://dummyimage.com/247x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Charissa', 'Branni', 'http://dummyimage.com/168x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Caressa', 'Hambidge', 'http://dummyimage.com/130x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Lisa', 'Rome', 'http://dummyimage.com/129x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Klara', 'Gavrieli', 'http://dummyimage.com/229x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Bellanca', 'Frobisher', 'http://dummyimage.com/155x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Clemmy', 'Norcock', 'http://dummyimage.com/132x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Dalli', 'Drinkale', 'http://dummyimage.com/241x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Weider', 'Monkton', 'http://dummyimage.com/162x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Rosalyn', 'Rosenstock', 'http://dummyimage.com/153x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Salomi', 'Skirling', 'http://dummyimage.com/233x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Wald', 'Muzzullo', 'http://dummyimage.com/106x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Duane', 'Danelutti', 'http://dummyimage.com/185x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Saunderson', 'Dorkens', 'http://dummyimage.com/114x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Clevey', 'Kos', 'http://dummyimage.com/190x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Rustie', 'Durnell', 'http://dummyimage.com/237x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Conan', 'Culver', 'http://dummyimage.com/165x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Therine', 'Blare', 'http://dummyimage.com/239x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Laurella', 'McRobert', 'http://dummyimage.com/177x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Prissie', 'Dimitriev', 'http://dummyimage.com/180x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Valaree', 'Francello', 'http://dummyimage.com/122x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Britteny', 'Douris', 'http://dummyimage.com/233x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Archie', 'Steptoe', 'http://dummyimage.com/189x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Bertha', 'Witz', 'http://dummyimage.com/220x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Felizio', 'Cough', 'http://dummyimage.com/102x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Farrel', 'Vittore', 'http://dummyimage.com/107x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Ricky', 'Pinniger', 'http://dummyimage.com/121x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Gwyneth', 'Delatour', 'http://dummyimage.com/146x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Cathyleen', 'Dewing', 'http://dummyimage.com/128x100.png/dddddd/000000');
insert into PLAYERS (firstName, lastName, picture) values ('Alan', 'Brister', 'http://dummyimage.com/135x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Julianna', 'Karran', 'http://dummyimage.com/128x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Adaline', 'Beedon', 'http://dummyimage.com/103x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Ula', 'Boal', 'http://dummyimage.com/121x100.png/ff4444/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Nicole', 'MacAlpine', 'http://dummyimage.com/119x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Kerwin', 'Bachanski', 'http://dummyimage.com/177x100.png/5fa2dd/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Morry', 'Coogan', 'http://dummyimage.com/196x100.png/cc0000/ffffff');
insert into PLAYERS (firstName, lastName, picture) values ('Corissa', 'Files', 'http://dummyimage.com/199x100.png/cc0000/ffffff');


-- TEAMS
insert into TEAMS (teamName) values ('Philippines');
insert into TEAMS (teamName) values ('Kosovo');
insert into TEAMS (teamName) values ('Portugal');
insert into TEAMS (teamName) values ('Indonesia');
insert into TEAMS (teamName) values ('China');
insert into TEAMS (teamName) values ('Guatemala');
insert into TEAMS (teamName) values ('Portugal');
insert into TEAMS (teamName) values ('Colombia');
insert into TEAMS (teamName) values ('Poland');
insert into TEAMS (teamName) values ('Taiwan');
insert into TEAMS (teamName) values ('Poland');
insert into TEAMS (teamName) values ('Philippines');
insert into TEAMS (teamName) values ('Argentina');
insert into TEAMS (teamName) values ('Indonesia');
insert into TEAMS (teamName) values ('Indonesia');
insert into TEAMS (teamName) values ('Armenia');
insert into TEAMS (teamName) values ('Albania');
insert into TEAMS (teamName) values ('Sweden');
insert into TEAMS (teamName) values ('Philippines');
insert into TEAMS (teamName) values ('China');
insert into TEAMS (teamName) values ('Czech Republic');
insert into TEAMS (teamName) values ('France');
insert into TEAMS (teamName) values ('Colombia');
insert into TEAMS (teamName) values ('Russia');
insert into TEAMS (teamName) values ('China');
insert into TEAMS (teamName) values ('Philippines');
insert into TEAMS (teamName) values ('Ukraine');
insert into TEAMS (teamName) values ('Indonesia');
insert into TEAMS (teamName) values ('Belize');
insert into TEAMS (teamName) values ('Thailand');


-- PLAYER ROLES
insert into PLAYER_ROLES (nameRole) values ('pitcher');
insert into PLAYER_ROLES (nameRole) values ('catcher');
insert into PLAYER_ROLES (nameRole) values ('first baseman');
insert into PLAYER_ROLES (nameRole) values ('second baseman');
insert into PLAYER_ROLES (nameRole) values ('third baseman');
insert into PLAYER_ROLES (nameRole) values ('shortstop');
insert into PLAYER_ROLES (nameRole) values ('left fielder');
insert into PLAYER_ROLES (nameRole) values ('center fielder');
insert into PLAYER_ROLES (nameRole) values ('right fielder');


-- SERIES
insert into SERIES (description, publicationDate) values ('S1', '2020-04-11');
insert into SERIES (description, publicationDate) values ('S2', '2011-03-28');
insert into SERIES (description, publicationDate) values ('S3', '2009-08-17');
insert into SERIES (description, publicationDate) values ('S4', '2001-01-11');
insert into SERIES (description, publicationDate) values ('S5', '2004-11-21');
insert into SERIES (description, publicationDate) values ('S6', '2007-10-03');
insert into SERIES (description, publicationDate) values ('S7', '2000-02-21');
insert into SERIES (description, publicationDate) values ('S8', '2019-07-27');
insert into SERIES (description, publicationDate) values ('S1', '2012-01-21');


-- collections
insert into COLLECTIONS (description, fk_idSerie) values ('Champions', 4);
insert into COLLECTIONS (description, fk_idSerie) values ('mvp', 5);
insert into COLLECTIONS (description, fk_idSerie) values ('runners', 8);
insert into COLLECTIONS (description, fk_idSerie) values ('home-run', 2);
insert into COLLECTIONS (description, fk_idSerie) values ('classics', 9);
insert into COLLECTIONS (description, fk_idSerie) values ('legend', 9);
insert into COLLECTIONS (description, fk_idSerie) values ('hall-of-fame', 6);
insert into COLLECTIONS (description, fk_idSerie) values ('Champions', 2);
insert into COLLECTIONS (description, fk_idSerie) values ('mvp', 6);
insert into COLLECTIONS (description, fk_idSerie) values ('runners', 8);
insert into COLLECTIONS (description, fk_idSerie) values ('home-run', 6);
insert into COLLECTIONS (description, fk_idSerie) values ('classics', 5);
insert into COLLECTIONS (description, fk_idSerie) values ('legend', 5);
insert into COLLECTIONS (description, fk_idSerie) values ('hall-of-fame', 2);
insert into COLLECTIONS (description, fk_idSerie) values ('Champions', 1);
insert into COLLECTIONS (description, fk_idSerie) values ('mvp', 4);
insert into COLLECTIONS (description, fk_idSerie) values ('runners', 3);
insert into COLLECTIONS (description, fk_idSerie) values ('home-run', 3);
insert into COLLECTIONS (description, fk_idSerie) values ('classics', 3);
insert into COLLECTIONS (description, fk_idSerie) values ('legend', 8);


-- player-career
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2002-01-01', 62, 14, 5);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2001-01-01', 58, 14, 2);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2001-01-01', 7, 13, 9);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2002-01-01', 92, 12, 7);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2009-01-01', 32, 22, 2);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2000-01-01', 3, 18, 8);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2008-01-01', 55, 22, 1);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2007-01-01', 10, 15, 6);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2001-01-01', 69, 25, 2);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2002-01-01', 80, 29, 5);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2006-01-01', 4, 23, 4);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2000-01-01', 39, 5, 8);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2009-01-01', 71, 26, 3);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2003-01-01', 75, 17, 8);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2000-01-01', 10, 1, 4);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2001-01-01', 26, 29, 6);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2003-01-01', 17, 21, 7);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2009-01-01', 79, 19, 9);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2003-01-01', 62, 23, 7);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2000-01-01', 32, 25, 6);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2005-01-01', 92, 4, 1);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2008-01-01', 7, 30, 8);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2006-01-01', 48, 7, 6);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2001-01-01', 35, 6, 2);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2005-01-01', 70, 6, 5);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2003-01-01', 72, 3, 1);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2007-01-01', 21, 11, 8);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2009-01-01', 81, 5, 7);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2004-01-01', 1, 5, 5);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2007-01-01', 64, 1, 5);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2006-01-01', 68, 25, 4);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2009-01-01', 19, 6, 6);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2000-01-01', 4, 13, 6);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2003-01-01', 97, 8, 3);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2007-01-01', 57, 11, 7);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2008-01-01', 74, 23, 2);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2002-01-01', 79, 30, 6);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2004-01-01', 1, 13, 2);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2009-01-01', 50, 4, 9);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2008-01-01', 90, 18, 6);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2003-01-01', 65, 19, 5);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2007-01-01', 53, 2, 4);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2000-01-01', 47, 14, 7);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2004-01-01', 77, 19, 5);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2009-01-01', 24, 21, 6);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2001-01-01', 88, 16, 9);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2001-01-01', 6, 6, 9);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2003-01-01', 26, 21, 4);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2003-01-01', 100, 2, 4);
insert into player_career (season, fk_idPlayer, fk_idTeam, fk_idPlayerRole) values ('2006-01-01', 20, 4, 2);


-- cards
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (3, 6, 3);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (2, 7, 38);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (4, 3, 26);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (1, 8, 37);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (2, 1, 33);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 3, 3);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (2, 3, 47);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 4, 22);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (4, 8, 22);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (2, 1, 11);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (4, 6, 10);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (2, 2, 30);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 5, 29);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 7, 17);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (4, 1, 31);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 4, 17);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (4, 5, 41);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 4, 40);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (3, 7, 46);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (1, 9, 16);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (4, 5, 25);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (2, 2, 22);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 8, 45);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 8, 4);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 1, 32);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (2, 6, 40);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 1, 24);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (4, 9, 19);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 9, 38);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (4, 7, 24);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (4, 5, 49);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 2, 40);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 9, 15);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (3, 1, 19);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 1, 17);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 4, 43);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 9, 17);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 1, 31);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (3, 1, 43);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 9, 47);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (3, 9, 27);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (2, 7, 45);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (3, 8, 43);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 6, 17);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (4, 5, 23);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (3, 2, 14);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (2, 3, 38);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (5, 1, 26);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (2, 9, 40);
insert into cards (fk_idRarity, fk_idSerie, fk_playerCareer) values (2, 5, 23);



-- collections_cards
insert into collections_cards (fk_idCard, fk_idCollection) values (20, 1);
insert into collections_cards (fk_idCard, fk_idCollection) values (21, 2);
insert into collections_cards (fk_idCard, fk_idCollection) values (7, 6);
insert into collections_cards (fk_idCard, fk_idCollection) values (19, 6);
insert into collections_cards (fk_idCard, fk_idCollection) values (50, 6);
insert into collections_cards (fk_idCard, fk_idCollection) values (18, 7);
insert into collections_cards (fk_idCard, fk_idCollection) values (8, 8);
insert into collections_cards (fk_idCard, fk_idCollection) values (31, 8);
insert into collections_cards (fk_idCard, fk_idCollection) values (42, 8);
insert into collections_cards (fk_idCard, fk_idCollection) values (47, 8);
insert into collections_cards (fk_idCard, fk_idCollection) values (10, 9);
insert into collections_cards (fk_idCard, fk_idCollection) values (25, 9);
insert into collections_cards (fk_idCard, fk_idCollection) values (18, 11);
insert into collections_cards (fk_idCard, fk_idCollection) values (30, 11);
insert into collections_cards (fk_idCard, fk_idCollection) values (32, 11);
insert into collections_cards (fk_idCard, fk_idCollection) values (16, 12);
insert into collections_cards (fk_idCard, fk_idCollection) values (47, 12);
insert into collections_cards (fk_idCard, fk_idCollection) values (8, 13);
insert into collections_cards (fk_idCard, fk_idCollection) values (4, 14);
insert into collections_cards (fk_idCard, fk_idCollection) values (38, 14);
insert into collections_cards (fk_idCard, fk_idCollection) values (40, 14);
insert into collections_cards (fk_idCard, fk_idCollection) values (8, 15);
insert into collections_cards (fk_idCard, fk_idCollection) values (18, 15);
insert into collections_cards (fk_idCard, fk_idCollection) values (45, 15);
insert into collections_cards (fk_idCard, fk_idCollection) values (25, 16);
insert into collections_cards (fk_idCard, fk_idCollection) values (16, 17);
insert into collections_cards (fk_idCard, fk_idCollection) values (29, 17);
insert into collections_cards (fk_idCard, fk_idCollection) values (42, 18);
insert into collections_cards (fk_idCard, fk_idCollection) values (11, 19);
insert into collections_cards (fk_idCard, fk_idCollection) values (36, 20);


-- user-card
insert into users_cards (fk_idCard, fk_idUser, amount) values (26, 32, 2);
insert into users_cards (fk_idCard, fk_idUser, amount) values (5, 29, 3);
insert into users_cards (fk_idCard, fk_idUser, amount) values (40, 3, 3);
insert into users_cards (fk_idCard, fk_idUser, amount) values (31, 12, 4);
insert into users_cards (fk_idCard, fk_idUser, amount) values (33, 10, 7);
insert into users_cards (fk_idCard, fk_idUser, amount) values (20, 19, 3);
insert into users_cards (fk_idCard, fk_idUser, amount) values (8, 33, 4);
insert into users_cards (fk_idCard, fk_idUser, amount) values (35, 20, 10);
insert into users_cards (fk_idCard, fk_idUser, amount) values (32, 11, 10);
insert into users_cards (fk_idCard, fk_idUser, amount) values (35, 23, 4);
insert into users_cards (fk_idCard, fk_idUser, amount) values (2, 25, 8);
insert into users_cards (fk_idCard, fk_idUser, amount) values (37, 36, 1);
insert into users_cards (fk_idCard, fk_idUser, amount) values (15, 11, 1);
insert into users_cards (fk_idCard, fk_idUser, amount) values (26, 4, 9);
insert into users_cards (fk_idCard, fk_idUser, amount) values (4, 30, 7);
insert into users_cards (fk_idCard, fk_idUser, amount) values (39, 24, 2);
insert into users_cards (fk_idCard, fk_idUser, amount) values (19, 29, 2);
insert into users_cards (fk_idCard, fk_idUser, amount) values (3, 15, 3);
insert into users_cards (fk_idCard, fk_idUser, amount) values (37, 22, 5);
insert into users_cards (fk_idCard, fk_idUser, amount) values (21, 11, 2);
insert into users_cards (fk_idCard, fk_idUser, amount) values (2, 24, 6);
insert into users_cards (fk_idCard, fk_idUser, amount) values (12, 3, 4);
insert into users_cards (fk_idCard, fk_idUser, amount) values (26, 15, 5);
insert into users_cards (fk_idCard, fk_idUser, amount) values (19, 2, 9);
insert into users_cards (fk_idCard, fk_idUser, amount) values (26, 17, 5);
insert into users_cards (fk_idCard, fk_idUser, amount) values (32, 13, 5);
insert into users_cards (fk_idCard, fk_idUser, amount) values (15, 15, 10);
insert into users_cards (fk_idCard, fk_idUser, amount) values (24, 22, 4);
insert into users_cards (fk_idCard, fk_idUser, amount) values (36, 14, 4);
insert into users_cards (fk_idCard, fk_idUser, amount) values (1, 25, 5);
insert into users_cards (fk_idCard, fk_idUser, amount) values (30, 15, 3);
insert into users_cards (fk_idCard, fk_idUser, amount) values (19, 28, 8);
insert into users_cards (fk_idCard, fk_idUser, amount) values (21, 18, 5);
insert into users_cards (fk_idCard, fk_idUser, amount) values (43, 35, 7);
insert into users_cards (fk_idCard, fk_idUser, amount) values (5, 3, 10);
insert into users_cards (fk_idCard, fk_idUser, amount) values (8, 22, 2);
insert into users_cards (fk_idCard, fk_idUser, amount) values (30, 13, 3);
insert into users_cards (fk_idCard, fk_idUser, amount) values (45, 6, 6);
insert into users_cards (fk_idCard, fk_idUser, amount) values (33, 23, 4);
insert into users_cards (fk_idCard, fk_idUser, amount) values (33, 24, 1);
insert into users_cards (fk_idCard, fk_idUser, amount) values (50, 18, 4);
insert into users_cards (fk_idCard, fk_idUser, amount) values (4, 28, 10);
insert into users_cards (fk_idCard, fk_idUser, amount) values (29, 19, 4);
insert into users_cards (fk_idCard, fk_idUser, amount) values (41, 15, 6);
insert into users_cards (fk_idCard, fk_idUser, amount) values (13, 26, 5);
insert into users_cards (fk_idCard, fk_idUser, amount) values (34, 31, 7);
insert into users_cards (fk_idCard, fk_idUser, amount) values (50, 13, 2);
insert into users_cards (fk_idCard, fk_idUser, amount) values (10, 20, 4);
insert into users_cards (fk_idCard, fk_idUser, amount) values (9, 8, 5);
insert into users_cards (fk_idCard, fk_idUser, amount) values (21, 17, 6);